name: build-windows-dll

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build DLL (x64)
        shell: cmd
        run: >-
          cl /nologo /LD /O2 /EHsc /std:c++17
          /DWUFFS_IMG_BUILD
          /I dll
          dll\wuffs_img_dll.cc
          /Fe:wuffs_img.dll
          /link /DEFAULTLIB:advapi32

      - name: Collect artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifact | Out-Null
          Get-ChildItem -Path . -Filter "wuffs_img.*" | Copy-Item -Destination artifact -Force

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuffs_img-windows-x64
          path: artifact/*